### ISSUE TITLE
Issues when creating a monitored only zfs based filesystem

### ISSUE THREAD

**Issue by yhamidi** [intel-hpdd/Vagrantfiles#4]
1. Using the Vagrantfile from the vagrant repo, it is not possible to create a mirrored zpools (using two disks for each) on nodes mds1 and mds2.  The list below shows what /dev/disk/by-id available on these vagrant nodes after they were brought up.  When creating the zpools using these disks, it fails with following error:
the kernel failed to rescan the partition table: 16
cannot label 'sda': try using parted(8) and then provide a specific slice: -1

mds1:
ata-VBOX_HARDDISK_VB6850353a-1d6e34ca
ata-VBOX_HARDDISK_VB9df0741a-27f57e49
ata-VBOX_HARDDISK_VBcf85d343-bbf08e1b
ata-VBOX_HARDDISK_VBcf85d343-bbf08e1b-part1
ata-VBOX_HARDDISK_VBcf85d343-bbf08e1b-part2

mds2:
ata-VBOX_HARDDISK_VB61e9b3f8-8c86984c
ata-VBOX_HARDDISK_VB61e9b3f8-8c86984c-part1
ata-VBOX_HARDDISK_VB61e9b3f8-8c86984c-part2
ata-VBOX_HARDDISK_VB6850353a-1d6e34ca
ata-VBOX_HARDDISK_VB6850353a-1d6e34ca-part1
ata-VBOX_HARDDISK_VB6850353a-1d6e34ca-part9
ata-VBOX_HARDDISK_VB9df0741a-27f57e49
ata-VBOX_HARDDISK_VB9df0741a-27f57e49-part1
ata-VBOX_HARDDISK_VB9df0741a-27f57e49-part9

2. Vagrant node mds2 becomes unresponsive after creating a lustre filesystem as shown below. The reboot, reload, and ssh will fail even though the status is running.  The usual error is show below and the only way to recover on this node is to destroy and and bring it backup again.

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

[root@ct7-mds2 vagrant]# zpool list
NAME   SIZE  ALLOC   FREE  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
mds   4.97G    65K  4.97G         -     0%     0%  1.00x  ONLINE  -
[root@ct7-mds2 vagrant]# mkfs.lustre --reformat --failover 10.73.20.11@tcp  --mdt --backfstype=zfs --fsname=zfsmo --index=0 --mgsnode=10.73.20.11@tcp,10.73.20.12@tcp mds/mdt0

   Permanent disk data:
Target:     zfsmo:MDT0000
Index:      0
Lustre FS:  zfsmo
Mount type: zfs
Flags:      0x61
              (MDT first_time update )
Persistent mount opts: 
Parameters: failover.node=10.73.20.11@tcp mgsnode=10.73.20.11@tcp,10.73.20.12@tcp
mkfs_cmd = zfs create -o canmount=off -o xattr=sa mds/mdt0
Writing mds/mdt0 properties
  lustre:failover.node=10.73.20.11@tcp
  lustre:mgsnode=10.73.20.11@tcp,10.73.20.12@tcp
  lustre:version=1
  lustre:flags=97
  lustre:index=0
  lustre:fsname=zfsmo
  lustre:svname=zfsmo:MDT0000
[root@ct7-mds2 vagrant]# mkdir -p /lustre/zfsmo/mdt0
[root@ct7-mds2 vagrant]# mount -t lustre mds/mdt0 /lustre/zfsmo/mdt0
mount.lustre: mount mds/mdt0 at /lustre/zfsmo/mdt0 failed: Connection timed out

**Comment by jgrund** [comment]
@yhamidi Is any of this still an issue?

**Comment by yhamidi** [comment]
This is no longer an issue. Mirrored zpools on mds1 and mds2 which requires 4 disks is not required.  
Closing this issue
